services:
  - type: web
    name: backend
    runtime: node
    runtimeVersion: 22.22.0
    buildCommand: ./render-build.sh
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
