services:
  - type: web
    name: backend
    runtime: node
    plan: free
    buildCommand: bun install && bunx tsc
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
